version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d8:b2:08:9a:95:9d:c6:ec:7f:4c:a6:a9:f6:6d:99:0e"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t jparrauguina/parrita_docker:$CIRCLE_SHA1 .
      - run: docker push jparrauguina/parrita_docker:$CIRCLE_SHA1
      - run: ssh -v -o StrictHostkeyChecking=no root@35.242.138.166 "/bin/bash /root/dock/deploy.sh $CIRCLE_SHA1"