version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fe:0b:2f:53:7e:ed:58:c0:03:57:e5:01:32:48:16:1b"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t jparrauguina/parrita_docker:$CIRCLE_SHA1 .
      - run: docker push jparrauguina/parrita_docker:$CIRCLE_SHA1
      - run: ssh -v -o StrictHostkeyChecking=no root@35.242.138.166 /bin/bash /root/docker/deploy.sh $CIRCLE_SHA1