version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:b4:12:f1:80:f3:06:9f:de:ef:1b:9f:b9:57:8b:5e"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t jparrauguina/parrita_docker:$CIRCLE_SHA1 .
      - run: docker push jparrauguina/parrita_docker:$CIRCLE_SHA1
      - run: ssh -o StrictHostkeyChecking=no root@35.242.138.166 "/bin/bash /root/dock/deploy.sh $CIRCLE_SHA1"